import { execSync } from "node:child_process";
import { readFileSync, writeFileSync, existsSync, mkdirSync, rmSync } from "node:fs";
import { join, resolve } from "node:path";
import { createHash } from "node:crypto";

const ROOT_DIR = resolve(__dirname, "../../..");
const CONTRACTS_DIR = join(ROOT_DIR, "contracts");
const WASM_PATH = join(
  CONTRACTS_DIR,
  "target/wasm32-unknown-unknown/release/yield_vault.wasm"
);
const TEMP_BINDINGS_DIR = join(ROOT_DIR, ".tmp_bindings_yield_vault");
const OUTPUT_FILE = join(ROOT_DIR, "packages/sdk/src/generated/yield_vault.ts");

function getWasmSpecHash(wasmPath: string): string {
  const fileBuffer = readFileSync(wasmPath);
  return createHash("sha256").update(fileBuffer).digest("hex");
}

export function generateBindings(): { specHash: string; cliVersion: string } {
  console.log("--> Ensuring YieldVault WASM is built...");
  if (!existsSync(WASM_PATH)) {
    execSync("cargo build --target wasm32-unknown-unknown --release --package yield_vault", {
      cwd: CONTRACTS_DIR,
      stdio: "inherit",
    });
  }

  const specHash = getWasmSpecHash(WASM_PATH);
  let cliVersion = "unknown";
  try {
    cliVersion = execSync("stellar --version", { encoding: "utf-8" })
      .trim()
      .replace(/\s+/g, " ");
  } catch {
    console.warn("Warning: stellar CLI not found in PATH");
  }

  console.log(`--> Extracting Soroban spec from WASM (hash: ${specHash.slice(0, 12)}...)`);
  execSync(
    `stellar contract bindings typescript --wasm "${WASM_PATH}" --output-dir "${TEMP_BINDINGS_DIR}" --overwrite`,
    { cwd: ROOT_DIR, stdio: "inherit" }
  );

  let rawGenerated = readFileSync(join(TEMP_BINDINGS_DIR, "src/index.ts"), "utf-8");

  // Replace window.Buffer to avoid TS errors when DOM lib is absent and prevent polyfill leakage
  rawGenerated = rawGenerated.replace(
    /if\s*\(\s*typeof\s+window\s*!==\s*"undefined"\s*\)\s*\{\s*\/\/\s*@ts-ignore\s+Buffer\s+exists\s+window\.Buffer\s*=\s*window\.Buffer\s*\|\|\s*Buffer;\s*\}/g,
    `const _globalObj = typeof globalThis !== "undefined" ? (globalThis as any) : {};\nif (_globalObj && typeof _globalObj.Buffer === "undefined") {\n  _globalObj.Buffer = Buffer;\n}`
  );

  const header = `/**
 * AUTOGENERATED SOROBAN CONTRACT BINDINGS FOR YIELD_VAULT
 *
 * DO NOT EDIT DIRECTLY.
 * Pinned Spec Hash: ${specHash}
 * Stellar CLI Version: ${cliVersion}
 * Generated At: ${new Date().toISOString()}
 */

export const YIELD_VAULT_SPEC_HASH = "${specHash}";
export const BINDING_GENERATOR_VERSION = "${cliVersion}";

`;

  const finalCode = header + rawGenerated;

  mkdirSync(join(ROOT_DIR, "packages/sdk/src/generated"), { recursive: true });
  writeFileSync(OUTPUT_FILE, finalCode, "utf-8");
  if (existsSync(TEMP_BINDINGS_DIR)) {
    rmSync(TEMP_BINDINGS_DIR, { recursive: true, force: true });
  }

  console.log(`--> Successfully generated bindings at ${OUTPUT_FILE}`);
  return { specHash, cliVersion };
}

if (require.main === module) {
  generateBindings();
}
